# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Movie_Posters', 'Movie_Posters'), ('Music_TV_Posters', 'Music_TV_Posters'), ('Art_Prints', 'Art_Prints')], max_length=250),
        ),
    ]
