# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200507_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1.00),
        ),
    ]
